// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xucbdjhhdioaicwqdcgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Y2JkamhoZGlvYWljd3FkY2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODI5OTEsImV4cCI6MjA2Mzg1ODk5MX0.-he70ecrjurCKksIl5ZPSBjiiJlOiyTxtBwSBmbEif4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);